Part A- Create a Notebook to demonstrate NumPy Operations


In [1]:
import numpy as np


Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
array = np.arange(1, 21, 3)#(start of an array, end of an array, step size)
print(array)


[ 1  4  7 10 13 16 19]


Create a new array of shape 3 with random numbers between 0 and 1.

In [4]:
array = np.random.rand(3)
print(array)


[0.92007925 0.62930122 0.06395103]


Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

    Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.


In [7]:
array_2D = np.array([[10,20,45], [30,12,16], [42,17,56]])

firstTwoRows = array_2D[:2]
lastTwoRows  = array_2D[-2:]

print(firstTwoRows)
print(lastTwoRows)


[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [8]:
array1 = np.array([[10, 20], [45, 30]])
array2 = np.array([[12, 16], [42, 17]])

# Stack the arrays vertically
stack_vertically = np.vstack((array1, array2))
print(stacked_vertically)

# Stack the arrays horizontally
stack_horizontally = np.hstack((array1, array2))
print(stacked_horizontally)

# Split the arrays into smaller arrays
split_arrays = np.split(stacked_vertically, 2, axis=1)
print(split_arrays)

[[10 20]
 [45 30]
 [12 16]
 [42 17]]
[[10 20 12 16]
 [45 30 42 17]]
[array([[10],
       [45],
       [12],
       [42]]), array([[20],
       [30],
       [16],
       [17]])]


Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),

    Is it possible to multiply these matrices?
    Demonstrate the case when it is not possible to.


In [10]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

product = np.dot(X, Y)
print(product)

[[70 28]
 [70 30]
 [60 26]]


For the multiplication to not be possible it would mean that the number of columns in the first matrix was not equal to the number of rows in the second matrix. An example case would be:

In [13]:
X = np.array([[5, 7, 2], [4, 5]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

product = np.dot(X, Y)
print(product)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),

    Find the Shape, Number of dimensions of vector x.
    Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [14]:
x = np.array([2, -1, -8])

print("Shape of x: ", x.shape)
print("Number of dimensions of x: ", x.ndim)

Shape of x:  (3,)
Number of dimensions of x:  1


In [15]:
x_reshaped = x.reshape(3,1)

print("Shape of x_reshaped: ", x_reshaped.shape)
print("Number of dimensions of x_reshaped: ", x_reshaped.ndim)

Shape of x_reshaped:  (3, 1)
Number of dimensions of x_reshaped:  2


In [17]:
y = np.array([3, 1, -2])
y_reshaped = y.reshape(3,1)

print("Shape of y_reshaped: ", y_reshaped.shape)
print("Number of dimensions of y_reshaped: ", y_reshaped.ndim)

Shape of y_reshaped:  (3, 1)
Number of dimensions of y_reshaped:  2


How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [20]:
#scalar value 5 is broadcast across the entire matrix A.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A - 5
print(B)

#1x3 matrix y is broadcast across the 3x1 matrix x.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = x * y
print('\n',z)



[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]

 [ 4 10 18]


Part B- Linear Equations

Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.

Part B.1

    4x + y - 2z = 10
    2x - 3y + 2z = -4
    x + 2y + 3z = 6


In [23]:
A = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])

# Define the matrix of constants
b = np.array([10, -4, 6])

det = np.linalg.det(A)

# Check if the system is singular
if det == 0:
    print("The system is singular and has no unique solution.")
else:
    # Calculate the solution using numpy.linalg.solve()
    x = np.linalg.solve(A, b)
    print("The solution of the system is:", x)

The solution of the system is: [ 1.8  2.4 -0.2]


Part B.2

    2x - y + 3z + 4w = 10
    4x - 2y + 6z + 8w = 20
    3x + y - 2z + 2w = 3
    x + 3y - 4z + w = -1


In [24]:
A = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])

b = np.array([10, 20, 3, -1])

det = np.linalg.det(A)

# Check if the system is singular
if det == 0:
    print("The system is singular and has no unique solution.")
else:
    # Calculate the solution using numpy.linalg.solve()
    x = np.linalg.solve(A, b)
    print("The solution of the system is:", x)

The system is singular and has no unique solution.
